name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      working-directory: functions
    
    - name: Run linting
      run: npm run lint -- --fix
      working-directory: functions
    
    # - name: Run type checking
    #   run: npx tsc --noEmit
    
    - name: Run tests
      run: npm run test -- --run
    
    - name: Build application
      run: npm run build
